### ISSUE TITLE
Hope for code!

### ISSUE THREAD

**Issue by DDgogogo** [thu-ml/DiffusionBridge#1]
Thank you for this work, and I hope for your code.

**Comment by zhengkw18** [comment]
Thank you for your interest in our work! Hopefully we can release the code this week.

**Comment by DDgogogo** [comment]
> 感谢您对我们工作的关注！希望我们本周能发布代码。

Thanks, hope for your code!

**Comment by zhengkw18** [comment]
Thanks for your patience! We took some time cleaning and rearranging the code. We have released the sampling part, and plan to release the training code in the future.
